<a href="https://colab.research.google.com/github/ENG19CS0334-TEJAAL-M/AI-ML/blob/main/SEM1/ML/Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# importing libraries
import numpy as nm
import matplotlib.pyplot as mtp
import pandas as pd

In [2]:
#importing datasets
data_set= pd.read_csv('50_CompList.csv')
data_set

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  774031.10
1   162597.70       151377.59        443898.53  California  758873.82
2   153441.51       101145.55        407934.54     Florida  662521.60
3   144372.41       118671.85        383199.62    New York  646243.88
4   142107.34        91391.77        366168.42     Florida  599667.53
5   131876.90        99814.71        362861.36    New York  594552.97
6   134615.46       147198.87        127716.82  California  409530.15
7   130298.13       145530.06        323876.68     Florida  599705.87
8   120542.52       148718.95        311613.29    New York  580874.76
9   123334.88       108679.17        304981.62  California  536995.67
10  101913.08       110594.11        229160.95     Florida  441668.14
11  100671.96        91790.61        249744.55  California  441207.12
12   93863.75       127320.38        249839.44     Florida  471023.57
13   91992.39       135495.07        252664.93  California  480152.39
14  119943.24       156547.42        256512.92     Florida  532003.58
15  114523.61       122616.84        261776.23    New York  498916.68
16   78013.11       121597.55        264346.06  California  464956.72
17   94657.16       145077.58        282574.31    New York  522309.05
18   91749.16       114175.79        294919.57     Florida  500844.52
19   86419.70       153514.11             0.00    New York  239933.81
20   76253.86       113867.30        298664.47  California  488785.63
21   78389.47       153773.43        299737.29    New York  531900.19
22   73994.56       122782.75        303319.26     Florida  497096.57
23   67532.53       105751.03        304768.73     Florida  477052.29
24   77044.01        99281.34        140574.81    New York  316899.16
25   64664.71       139553.16        137962.62  California  351180.49
26   75328.87       144135.98        134050.07     Florida  351514.92
27   72107.60       127864.55        353183.81    New York  553155.96
28   66051.52       182645.56        118148.20     Florida  361845.28
29   65605.48       153032.06        107138.38    New York  325775.92
30   61994.48       115641.28         91131.24     Florida  268766.00
31   61136.38       152701.92         88218.23    New York  312056.53
32   63408.86       129219.61         46085.25  California  219713.72
33   55493.95       103057.49        214634.81     Florida  373186.25
34   46426.07       157693.92        210797.67  California  414917.66
35   46014.02        85047.44        205517.64    New York  331579.10
36   28663.76       127056.21        201126.82     Florida  356847.79
37   44069.95        51283.14        197029.42  California  291382.51
38   20229.59        65947.93        185265.10    New York  271442.62
39   38558.51        82982.09        174999.30  California  296539.90
40   28754.33       118546.05        172795.67  California  319096.05
41   27892.92        84710.77        164470.71     Florida  277074.40
42   23640.93        96189.63        148001.11  California  267831.67
43   15505.73       127382.30         35534.17    New York  178422.20
44   22177.74       154806.14         28334.72  California  205318.60
45    1000.23       124153.04          1903.93    New York  125057.20
46    1315.46       115816.21        297114.46     Florida  414246.13
47       0.00       135426.92             0.00  California  135426.92
48     542.05        51743.15             0.00    New York   52285.20
49       0.00       116983.80         45173.06  California  161156.86

In [3]:
#Extracting Independent and dependent Variable
x= data_set.iloc[:, :-1].values
y= data_set.iloc[:, 4].values

In [4]:
y

array([774031.1 , 758873.82, 662521.6 , 646243.88, 599667.53, 594552.97,
       409530.15, 599705.87, 580874.76, 536995.67, 441668.14, 441207.12,
       471023.57, 480152.39, 532003.58, 498916.68, 464956.72, 522309.05,
       500844.52, 239933.81, 488785.63, 531900.19, 497096.57, 477052.29,
       316899.16, 351180.49, 351514.92, 553155.96, 361845.28, 325775.92,
       268766.  , 312056.53, 219713.72, 373186.25, 414917.66, 331579.1 ,
       356847.79, 291382.51, 271442.62, 296539.9 , 319096.05, 277074.4 ,
       267831.67, 178422.2 , 205318.6 , 125057.2 , 414246.13, 135426.92,
        52285.2 , 161156.86])

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Assuming x contains your dataset, and column 4(index 3 in Python) is the categorical feature
# Create a ColumnTransformer to one-hot encode the categorical feature
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
x = np.array(ct.fit_transform(x))


In [6]:
x

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58

In [7]:
#avoiding the dummy variable trap:
x = x[:, 1:]

In [8]:
x

array([[0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 1.0, 94657.16, 145077.58, 282574.31],
       [1.0, 0.0, 91749.16, 114175.79, 294919.57],
       [0.0, 1.0, 86419.7

In [9]:
# Splitting the dataset into training and test set.
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.2, random_state=0)

In [10]:
#Fitting the MLR model to the training set:
from sklearn.linear_model import LinearRegression
model= LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [11]:
#Predicting the Test set result;
y_pred= model.predict(x_test)

In [12]:
r_sq = model.score(x_train, y_train)
print(f"coefficient of determination: {r_sq}")

coefficient of determination: 0.9996013834546972


In [13]:
print(f"intercept: {model.intercept_}")

intercept: -3320.8798987716436


In [14]:
print(f"coefficients: {model.coef_}")

coefficients: [-137.64405719  220.56840249    0.98574398    1.01568549    1.00897515]


In [15]:
#Advanced Linear Regression With statsmodels
import numpy as np
import statsmodels.api as sm

In [16]:
x = sm.add_constant(x_train)
x = np.array(x, dtype=float)

In [17]:
x[1,]

array([1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 4.6014020e+04,
       8.5047440e+04, 2.0551764e+05])

In [18]:
model = sm.OLS(y_train, x)

In [19]:
results = model.fit()

In [20]:
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 1.705e+04
Date:                Mon, 25 Aug 2025   Prob (F-statistic):           9.49e-57
Time:                        14:30:25   Log-Likelihood:                -381.22
No. Observations:                  40   AIC:                             774.4
Df Residuals:                      34   BIC:                             784.6
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -3320.8799   3084.487     -1.077      0.2